var COMMONJS_BANNER = "// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.\n";
var COMMONJS_HEAD = "\nmodule.exports = function(jQuery) {\n";
var COMMONJS_FOOT = "\n};\n";

module.exports = function(grunt) {

  grunt.initConfig({

    jshint: {
      all: ["Gruntfile.js", "src/**/*.js"]
    },

    less: {
      snackbar: {
        options: {
          paths: ["less"],
          sourceMap: true,
          sourceMapRootpath: "/",
          sourceMapFilename: "dist/snackbar.css.map",
          sourceMapURL: "snackbar.css.map"
        },
        files: {
          "dist/snackbar.css": "src/snackbar.less",
        }
      },
      themes: {
        options: {
          paths: ["themes-less"]
        },
        files: [{
          expand: true,
          cwd: "themes-less",
          src: "*.less",
          dest: "themes-css",
          ext: ".css"
        }]
      }
    },

    cssmin: {
      snackbar: {
        expand: true,
        cwd: "dist",
        src: ["*.css", "!*.min.css"],
        dest: "dist",
        ext: ".min.css"
      }
    },

    uglify: {
      options: {
        sourceMap: true
      },
      snackbar: {
        files: {
          "dist/snackbar.min.js": "src/snackbar.js"
        }
      }
    }

  });

  grunt.registerTask("commonjs", "Generate CommonJS entrypoint module in dist dir.", function () {
    var finalCode = COMMONJS_BANNER;
    
    finalCode += COMMONJS_HEAD;
    finalCode += grunt.file.read("src/snackbar.js");
    finalCode += COMMONJS_FOOT;
    grunt.file.write("dist/npm.js", finalCode);
  });
  
  grunt.loadNpmTasks("grunt-contrib-jshint");
  grunt.loadNpmTasks("grunt-contrib-copy");
  grunt.loadNpmTasks("grunt-contrib-cssmin");
  grunt.loadNpmTasks("grunt-contrib-uglify");
  grunt.loadNpmTasks("grunt-contrib-less");

  grunt.registerTask("test", ["jshint"]);
  grunt.registerTask("dist", ["less:snackbar", "cssmin:snackbar", "uglify:snackbar"]);
  grunt.registerTask("themes", ["less:themes"]);

};
